# Generated by Django 4.0.4 on 2024-01-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file_upload',
            field=models.FileField(upload_to=''),
        ),
    ]
