# Generated by Django 4.0.4 on 2024-01-08 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_filemanager_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemanager',
            name='auto_delete',
        ),
        migrations.RemoveField(
            model_name='filemanager',
            name='user_cache_key',
        ),
        migrations.AddField(
            model_name='filemanager',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
