# Generated by Django 4.0.4 on 2024-01-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_filemanager_auto_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file_upload',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
