# Generated by Django 4.0.4 on 2024-01-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_filemanager_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemanager',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='filemanager',
            name='file_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
